apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  owner: ultimate.ai
  kustomize-base: common-jobs

configMapGenerator:
- name: conf
  envs:
    - common.properties

resources:
- job.yaml
- service-account.yaml
