apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  owner: ultimate.ai
  kustomize-base: common

configMapGenerator:
- name: conf
  envs:
    - common.properties

vars:
  - name: APP_SERVICE
    objref:
      kind: Service
      name: service
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: APP_PORT
    objref:
      kind: Service
      name: service
      apiVersion: v1
    fieldref:
      fieldpath: spec.ports[0].port

resources:
- deployment.yaml
- service.yaml
- service-account.yaml
- ingress.yaml

configurations:
- kustomize_config.yaml
