varReference:
- path: spec/rules/http/paths/backend/service/name
  kind: Ingress
- path: spec/rules/http/paths/backend/service/port/number
  kind: Ingress
- path: spec/template/spec/containers/ports/containerPort
  kind: StatefulSet
- path: spec/template/spec/containers/readinessProbe/httpGet/port
  kind: StatefulSet
- path: spec/template/spec/securityContext/fsGroup
  kind: StatefulSet
