apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  owner: ultimate.ai
  kustomize-base: common-cronjobs

configMapGenerator:
- name: conf
  envs:
    - common.properties

resources:
- cronjob.yaml
- service-account.yaml
