varReference:
- path: spec/template/spec/containers/ports/containerPort
  kind: Deployment
- path: spec/template/spec/containers/readinessProbe/httpGet/port
  kind: Deployment
- path: spec/template/spec/securityContext/fsGroup
  kind: Deployment